           main: main.ms
          title: SampleBox2dCar
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core ui sqlite game2d box2d graphics
    orientation: landscape left
 remote-console: 
        version: 1.0
