           main: main.ms
          title: SampleRevoluteJoint
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core ui uix uix-skin media sqlite net game2d crypto box2d graphics sensor
    orientation: landscape left
        version: 1.0
