           main: main.ms
          title: HelloUI
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core graphics sqlite net crypto uix uix-skin
    orientation: portrait
        version: 1.0
