           main: main.ms
          title: SampleFireABird
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: ui sqlite box2d game2d core
    orientation: landscape left
 remote-console: 
        version: 1.0
