           main: main.ms
          title: SampleSceneTransitions
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core ui uix uix-skin media sql net game2d crypto box2d graphics sensor
    orientation: portrait
        version: 1.0
