           main: main.ms
          title: Sample animations
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core uix uix-skin media sql net game2d crypto box2d graphics
    orientation: portrait
        version: 0.0
