           main: main.ms
          title: SampleMouseJoint
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core uix-skin game2d box2d graphics
    orientation: portrait
        version: 1.0
